import { useState } from 'react';
export default function App(){
const [step,setStep]=useState(1);
const [idea,setIdea]=useState('');
const [duration,setDuration]=useState('60');
const [charStyle,setCharStyle]=useState('cinematic');
const [characters,setCharacters]=useState([]);
const [newChar,setNewChar]=useState({name:'',look:'',personality:''});
const [scenes,setScenes]=useState([]);
const [generating,setGenerating]=useState(false);
const [plan,setPlan]=useState('creator');
const addChar=()=>{ if(!newChar.name) return; setCharacters([...characters,{...newChar,id:Date.now()}]); setNewChar({name:'',look:'',personality:''}); };
const createScenes=()=>{ const c=Math.ceil(parseInt(duration)/8); setScenes(Array.from({length:c},(_,i)=>({id:i+1,status:'pending'}))); setStep(6); };
const gen=async()=>{ setGenerating(true); for(let i=0;i<scenes.length;i++){ setScenes(p=>p.map((s,j)=>j===i?{...s,status:'generating'}:s)); await new Promise(r=>setTimeout(r,800)); setScenes(p=>p.map((s,j)=>j===i?{...s,status:'done'}:s)); } setGenerating(false); setStep(7); };
return(
<div style={{background:'#050507',minHeight:'100vh',color:'#fff',fontFamily:'Inter, sans-serif'}}>
<header style={{display:'flex',justifyContent:'space-between',padding:'20px 40px',borderBottom:'1px solid #1a1a1a',alignItems:'center'}}>
<div style={{fontWeight:900,fontSize:'20px'}}>GABBOSS<span style={{color:'#FFD700'}}>.AI</span> FILM</div>
<div style={{display:'flex',gap:'12px'}}><span style={{background:'#FFD700',color:'#000',padding:'6px 14px',borderRadius:'20px',fontSize:'12px',fontWeight:700}}>250 CREDITS</span><button style={{background:'#fff',color:'#000',border:'none',padding:'8px 18px',borderRadius:'20px',fontWeight:700}}>Login</button></div>
</header>
<div style={{display:'flex',justifyContent:'center',gap:'8px',padding:'30px 20px',flexWrap:'wrap'}}>
{['Your Story','Sign Up','Plan','Create','Duration','Characters','Generate'].map((l,i)=><div key={i} style={{display:'flex',alignItems:'center',gap:'8px'}}><div style={{width:'28px',height:'28px',borderRadius:'50%',background:step>=i+1?'#FFD700':'#222',color:step>=i+1?'#000':'#666',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'12px',fontWeight:800}}>{i+1}</div><span style={{fontSize:'11px',color:step>=i+1?'#fff':'#555',fontWeight:600}}>{l}</span>{i<6&&<div style={{width:'20px',height:'1px',background:'#222',margin:'0 4px'}}/>}</div>)}
</div>
<div style={{maxWidth:'1100px',margin:'0 auto',padding:'0 20px 60px',display:'grid',gridTemplateColumns:'1.2fr 0.8fr',gap:'20px'}}>
<div style={{background:'rgba(255,255,255,0.04)',border:'1px solid #1e1e1e',borderRadius:'24px',padding:'30px'}}>
{step===1&&<div><h1 style={{fontSize:'42px',lineHeight:0.9,letterSpacing:'-2px',margin:0}}>YOUR STORY,<br/>YOUR FILM.</h1><p style={{color:'#888',marginTop:'10px'}}>Turn any idea into cinematic film. 30s to 3min.</p><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Describe your film idea... any genre" style={{width:'100%',height:'120px',background:'#0a0a0a',border:'1px solid #222',borderRadius:'16px',padding:'16px',color:'#fff',marginTop:'20px'}}/><button onClick={()=>setStep(2)} style={{marginTop:'20px',background:'#FFD700',color:'#000',border:'none',padding:'14px',borderRadius:'30px',fontWeight:800,width:'100%',cursor:'pointer'}}>CONTINUE →</button></div>}
{step===2&&<div><h2>Sign Up / Login</h2><input placeholder="Email" style={{width:'100%',background:'#0a0a0a',border:'1px solid #222',borderRadius:'12px',padding:'14px',color:'#fff',marginTop:'20px'}}/><input placeholder="Password" type="password" style={{width:'100%',background:'#0a0a0a',border:'1px solid #222',borderRadius:'12px',padding:'14px',color:'#fff',marginTop:'10px'}}/><button onClick={()=>setStep(3)} style={{marginTop:'20px',background:'#FFD700',color:'#000',border:'none',padding:'14px',borderRadius:'30px',fontWeight:800,width:'100%'}}>CONTINUE</button></div>}
{step===3&&<div><h2>Choose Plan</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:'10px',marginTop:'20px'}}>{[{id:'free',n:'Free',p:'$0'},{id:'creator',n:'Creator',p:'$19/mo'},{id:'studio',n:'Studio',p:'$99/mo'}].map(x=><div key={x.id} onClick={()=>setPlan(x.id)} style={{border:plan===x.id?'2px solid #FFD700':'1px solid #222',background:'#0a0a0a',borderRadius:'16px',padding:'16px',cursor:'pointer'}}><div style={{fontWeight:800}}>{x.n}</div><div style={{fontWeight:900}}>{x.p}</div></div>)}</div><button onClick={()=>setStep(4)} style={{marginTop:'20px',background:'#FFD700',color:'#000',border:'none',padding:'14px',borderRadius:'30px',fontWeight:800,width:'100%'}}>CHOOSE {plan.toUpperCase()} →</button></div>}
{step===4&&<div><h2>Create Film</h2><p style={{color:'#666',fontSize:'13px'}}>Idea: {idea}</p><input placeholder="Film Title" style={{width:'100%',background:'#0a0a0a',border:'1px solid #222',borderRadius:'12px',padding:'14px',color:'#fff',marginTop:'20px'}}/><button onClick={()=>setStep(5)} style={{marginTop:'20px',background:'#FFD700',color:'#000',border:'none',padding:'14px',borderRadius:'30px',fontWeight:800,width:'100%'}}>NEXT: DURATION →</button></div>}
{step===5&&<div><h2>Duration</h2><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:'10px',marginTop:'20px'}}>{[{v:'30',l:'30 sec'},{v:'60',l:'1 min'},{v:'120',l:'2 min'},{v:'180',l:'3 min Episode'}].map(d=><div key={d.v} onClick={()=>setDuration(d.v)} style={{border:duration===d.v?'2px solid #FFD700':'1px solid #222',background:'#0a0a0a',borderRadius:'16px',padding:'16px',cursor:'pointer'}}><div style={{fontWeight:800}}>{d.l}</div><div style={{fontSize:'11px',color:'#888'}}>{Math.ceil(parseInt(d.v)/8)} scenes • veo3.1</div></div>)}</div><div style={{marginTop:'20px'}}><div style={{fontSize:'12px',color:'#888'}}>Character Style</div><div style={{display:'flex',gap:'8px',marginTop:'8px'}}>{['realistic','cinematic','cartoon'].map(s=><button key={s} onClick={()=>setCharStyle(s)} style={{flex:1,padding:'10px',borderRadius:'20px',border:charStyle===s?'2px solid #FFD700':'1px solid #333',background:charStyle===s?'#FFD700':'transparent',color:charStyle===s?'#000':'#fff',fontWeight:700,textTransform:'capitalize',cursor:'pointer'}}>{s}</button>)}</div></div><button onClick={createScenes} style={{marginTop:'20px',background:'#FFD700',color:'#000',border:'none',padding:'14px',borderRadius:'30px',fontWeight:800,width:'100%'}}>CREATE {duration}s FILM →</button></div>}
{step===6&&<div><h2>Characters: ANYBODY</h2><p style={{color:'#666',fontSize:'12px'}}>Real, fictional, yourself - anybody. Style: {charStyle}</p><div style={{background:'#0a0a0a',border:'1px dashed #333',borderRadius:'16px',padding:'16px',marginTop:'16px'}}><input value={newChar.name} onChange={e=>setNewChar({...newChar,name:e.target.value})} placeholder="Who? e.g. John Wick, yourself, dragon" style={{width:'100%',background:'#111',border:'1px solid #222',borderRadius:'10px',padding:'12px',color:'#fff',marginBottom:'8px'}}/><input value={newChar.look} onChange={e=>setNewChar({...newChar,look:e.target.value})} placeholder="Look?" style={{width:'100%',background:'#111',border:'1px solid #222',borderRadius:'10px',padding:'12px',color:'#fff',marginBottom:'8px'}}/><input value={newChar.personality} onChange={e=>setNewChar({...newChar,personality:e.target.value})} placeholder="Personality?" style={{width:'100%',background:'#111',border:'1px solid #222',borderRadius:'10px',padding:'12px',color:'#fff',marginBottom:'8px'}}/><button onClick={addChar} style={{background:'#fff',color:'#000',border:'none',padding:'10px 16px',borderRadius:'20px',fontWeight:700,cursor:'pointer'}}>+ Add Character</button></div><div style={{marginTop:'12px'}}>{characters.map(c=><div key={c.id} style={{background:'#111',border:'1px solid #222',borderRadius:'12px',padding:'12px',marginBottom:'8px'}}><div style={{fontWeight:700}}>{c.name}</div><div style={{fontSize:'11px',color:'#888'}}>{c.look} • {c.personality} • {charStyle}</div></div>)}</div><div style={{marginTop:'20px'}}>{scenes.map(s=><div key={s.id} style={{background:'#0a0a0a',border:'1px solid #222',borderRadius:'12px',padding:'12px',marginBottom:'6px',display:'flex',justifyContent:'space-between'}}><span style={{fontSize:'12px'}}>Scene {s.id} - 8s</span><span style={{fontSize:'10px',color:s.status==='done'?'#0f0':s.status==='generating'?'#FFD700':'#555'}}>{s.status}</span></div>)}</div><button onClick={gen} disabled={generating} style={{marginTop:'20px',background:generating?'#333':'#FFD700',color:generating?'#888':'#000',border:'none',padding:'16px',borderRadius:'30px',fontWeight:900,width:'100%',cursor:'pointer'}}>{generating?'GENERATING...':`GENERATE ${duration}s FILM`}</button></div>}
{step===7&&<div><h2>Final Film Ready</h2><div style={{background:'#000',borderRadius:'16px',aspectRatio:'16/9',display:'flex',alignItems:'center',justifyContent:'center',border:'1px solid #222',marginTop:'16px'}}>🎬 {duration}s • {charStyle}</div><button style={{marginTop:'16px',background:'#FFD700',color:'#000',border:'none',padding:'12px',borderRadius:'20px',fontWeight:800,width:'100%'}}>Download & Publish S1 E1</button></div>}
</div>
<div><div style={{background:'rgba(255,215,0,0.05)',border:'1px solid rgba(255,215,0,0.2)',borderRadius:'24px',padding:'20px'}}><h3 style={{fontSize:'12px',color:'#FFD700'}}>LIVE PREVIEW</h3><div style={{background:'#000',borderRadius:'16px',aspectRatio:'16/9',marginTop:'12px',display:'flex',alignItems:'center',justifyContent:'center'}}><span style={{color:'#333',fontSize:'12px'}}>Preview</span></div><div style={{marginTop:'12px',fontSize:'12px',color:'#888'}}>Duration: {duration}s<br/>Style: {charStyle}<br/>Characters: {characters.length} anybody<br/>Model: veo3.1 with voice</div></div></div>
</div>
</div>
);
}
